  # base/gateway/deployment.yml
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: gateway
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: gateway
    template:
      metadata:
        labels:
          app: gateway
      spec:
        containers:
          - name: sentiment-gateway
            image: sentiment-gateway:v1
            imagePullPolicy: Never
            ports:
              - containerPort: 8000
            envFrom:
              - configMapRef:
                  name: gateway-config