apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  ENV: {{ .Values.global.environment | quote }}
  POSTGRES_DB: {{ .Values.postgres.dbName | quote }}
  REDIS_SERVICE_PORT: {{ .Values.redis.service.port | quote }}
  # Helm calculates the exact internal cluster domain for your services:
  POSTGRES_HOST: "{{ .Release.Name }}-postgres"
  REDIS_HOST: "{{ .Release.Name }}-redis"
  JOB_SERVICE_URL: "http://{{ .Release.Name }}-job:{{ .Values.job.service.port }}"