apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-job
spec:
  replicas: {{ .Values.job.replicaCount }}
  selector:
    matchLabels:
      app: job
  template:
    metadata:
      labels:
        app: job
    spec:
      containers:
        - name: sentiment-job
          image: "{{ .Values.job.image.repository }}:{{ .Values.job.image.tag }}"
          imagePullPolicy: {{ .Values.job.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.job.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secret