apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-job
spec:
  type: ClusterIP
  selector:
    app: job
  ports:
    - port: {{ .Values.job.service.port }}
      targetPort: {{ .Values.job.service.port }}